#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <TEMPLATE> <DOMAIN_NAME> <EMAIL_ADDRESS> <THRESHOLD"
  echo "e.g. $0 create billing.json example.com"
  exit 1
else
  DOMAIN_NAME=`echo $3 | sed -e 's/\./\-/g'`
  TEMPLATE_NAME=`echo $2 | sed -e 's/\.json//g'`
  export AWS_DEFAULT_PROFILE=aws-s3-$TEMPLATE_NAME
  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile $AWS_DEFAULT_PROFILE
  # Creates a CloudFormation stack for the s3 bucket website
  if [ $1 == "update" ]; then
    COMMAND=update-stack
  else
    COMMAND=create-stack
  fi
  aws cloudformation $COMMAND \
    --stack-name $TEMPLATE_NAME-$DOMAIN_NAME \
    --template-body file://$2 \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$3 \
ParameterKey=EmailAddress,ParameterValue=$4 \
ParameterKey=Threshold,ParameterValue=$5
fi
