#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <DOMAIN_NAME> <EMAIL_ADDRESS> <THRESHOLD>"
  echo "e.g. $0 create example.com me@eaxmple.com 100"
  exit 1
else
  DOMAIN_NAME=`echo $3 | sed -e 's/\./\-/g'`
  export AWS_DEFAULT_PROFILE=aws-billing
  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile $AWS_DEFAULT_PROFILE
  # Creates a CloudFormation stack for the s3 bucket website
  if [ $1 == "update" ]; then
    COMMAND=update-stack
  else
    COMMAND=create-stack
  fi
  aws cloudformation $COMMAND \
    --stack-name billing-$DOMAIN_NAME \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$2 \
ParameterKey=EmailAddress,ParameterValue=$3 \
ParameterKey=Threshold,ParameterValue=$4
fi
